apiVersion: apps/v1
kind: Deployment
metadata:
   name: spring-deployment

spec:
  replicas: 2
  selector:
      matchLabels:
            app: spring
  template:
      metadata:
        labels:
          app: spring

    spec:
      containers:
      - name: spring
        image: acrdockerimages101.azurecr.io/java-application:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: spring-Service
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

